// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

namespace Repository.Migrations
{
    [DbContext(typeof(BookStoreDBContext))]
<<<<<<< HEAD:BookStore_Backend/Repository/Migrations/20200509193558_initial.Designer.cs
    [Migration("20200509193558_initial")]
=======
    [Migration("20200511104325_initial")]
>>>>>>> 27c0d5b3e85f55f3be70bdfaeda7a57e78cf9e5a:BookStore_Backend/Repository/Migrations/20200511104325_initial.Designer.cs
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorName")
                        .IsRequired();

                    b.Property<bool>("Availability");

                    b.Property<string>("BookImage")
                        .IsRequired();

                    b.Property<double>("BookPrice");

                    b.Property<string>("BookTitle")
                        .IsRequired();

                    b.HasKey("BookID");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("Model.Cart", b =>
                {
                    b.Property<int>("CartID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookId");

                    b.Property<int>("NumOfCopies");

                    b.HasKey("CartID");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("Model.CustomerAdress", b =>
                {
<<<<<<< HEAD:BookStore_Backend/Repository/Migrations/20200509193558_initial.Designer.cs
                    b.Property<int>("CustomerId");
=======
                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd();
>>>>>>> 27c0d5b3e85f55f3be70bdfaeda7a57e78cf9e5a:BookStore_Backend/Repository/Migrations/20200511104325_initial.Designer.cs

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<string>("AddressType");

                    b.Property<string>("Citytown")
                        .IsRequired();

                    b.Property<string>("FullName")
                        .IsRequired();

                    b.Property<string>("Landmark");

                    b.Property<int>("PhoneNumber");

                    b.Property<int>("Pincode");

<<<<<<< HEAD:BookStore_Backend/Repository/Migrations/20200509193558_initial.Designer.cs
                    b.HasKey("CustomerId");
=======
                    b.HasKey("Email");
>>>>>>> 27c0d5b3e85f55f3be70bdfaeda7a57e78cf9e5a:BookStore_Backend/Repository/Migrations/20200511104325_initial.Designer.cs

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Model.User", b =>
                {
                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.HasKey("Email");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
